import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FavoriteListProvider } from "@/hooks/use-favorite-list";
import { ApolloProviderInit } from "@/lib/apollo-provider";
import "react-loading-skeleton/dist/skeleton.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ApolloProviderInit>
        <FavoriteListProvider>
          <body className={`${inter.variable} antialiased`}>
            <main className="section-container">{children}</main>
          </body>
        </FavoriteListProvider>
      </ApolloProviderInit>
    </html>
  );
}
